import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Footer from '../components/footer'
import Link from 'next/link'


const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          <strong>Welcome to My Sites</strong>
        </h1>
        <h2>
          My name is okta, nice to know you!
        </h2>


        <div className={styles.grid}>
          <div className={styles.card}>
            <Link href="/about" passHref>
              <a><h2>About</h2></a>
            </Link>
            <p>My journey</p>
          </div>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>About</h2>
            <p>My journey</p>
          </a>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>About</h2>
            <p>My journey</p>
          </a>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>About</h2>
            <p>My journey</p>
          </a>
        </div>
      </main>

      <Footer/>
    </div>
  )
}

export default Home
